services:
  shopping-list-editor:
    container_name: shoppinglisteditorcontainer
    build: .
    image: shoppinglisteditor:v1
    ports:
      - 80:80
    expose:
      - 80
    networks:
      - internalnet

networks:
  internalnet:
    driver: bridge
